import number from 'lodash-es/number';
import { Customer } from './customer';

export const customers: Customer[] = [
  {
    id: 1,
    firstname: 'Hugo',
    name: 'Brandt',
    country: 'AT',
    birthdate: '1974-05-12',
    mobilenumber: 1223345,
  },
  {
    id: 2,
    firstname: 'Badi',
    name: 'Raslan ',
    country: 'AT',
    birthdate: '2002-05-30',
    mobilenumber: 43660,
  },
  {
    id: 3,
    firstname: 'Fernandez',
    name: 'Rodriguez',
    country: 'ES',
    birthdate: '2001-01-05',
    mobilenumber: 435462,
  },
  {
    id: 4,
    firstname: 'Li',
    name: 'Qian',
    country: 'CN',
    birthdate: '1991-12-05',
    mobilenumber: 0,
  },
  {
    id: 5,
    firstname: 'Kakani',
    name: 'Bhattacharjee',
    country: 'IN',
    birthdate: '1989-10-11',
    mobilenumber: 786546,
  },
  {
    id: 6,
    firstname: 'Paul',
    name: 'Sullivan',
    country: 'UK',
    birthdate: '1995-05-31',
    mobilenumber: 0,
  },
  {
    id: 6,
    firstname: 'Samantha',
    name: 'Jones',
    country: 'US',
    birthdate: '2005-07-15',
    mobilenumber: 55555,
  },
  {
    id: 7,
    firstname: 'Renate',
    name: 'Hoffmann',
    country: 'DE',
    birthdate: '1987-11-15',
    mobilenumber: 6666,
  },
  {
    id: 8,
    firstname: 'Angelika',
    name: 'Hoffmann',
    country: 'DE',
    birthdate: '1987-11-15',
    mobilenumber: 6666,
  },
  {
    id: 9,
    firstname: 'Jean-Paul',
    name: 'Néro',
    country: 'FR',
    birthdate: '1955-09-21',
    mobilenumber: 6666,
  },
  {
    id: 10,
    firstname: 'Stefanie',
    name: 'Niederrein',
    country: 'AT',
    birthdate: '1997-03-12',
    mobilenumber: 6666,
  },
  {
    id: 11,
    firstname: 'Denise',
    name: 'Keller',
    country: 'CH',
    birthdate: '1998-07-01',
    mobilenumber: 6666,
  },
  {
    id: 12,
    firstname: 'Johan',
    name: 'Driekamp',
    country: 'NL',
    birthdate: '1958-09-12',
    mobilenumber: 6666,
  },
  {
    id: 13,
    firstname: 'Estefanía',
    name: 'Sánchez',
    country: 'ES',
    birthdate: '1985-10-10',
    mobilenumber: 6666,
  },
  {
    id: 14,
    firstname: 'John',
    name: 'Harrison',
    country: 'UK',
    birthdate: '1977-05-20',
    mobilenumber: 6666,
  },
  {
    id: 15,
    firstname: 'Helene',
    name: 'Ford',
    country: 'CA',
    birthdate: '1969-03-04',
    mobilenumber: 6666,
  },
  {
    id: 16,
    firstname: 'Jan',
    name: 'Janáček',
    country: 'CZ',
    birthdate: '2002-01-02',
    mobilenumber: 6666,
  },
  {
    id: 17,
    firstname: 'Knut',
    name: 'Eggen',
    country: 'NO',
    birthdate: '1999-07-17',
    mobilenumber: 6666,
  },
  {
    id: 18,
    firstname: 'Oskar',
    name: 'Sjögren',
    country: 'SE',
    birthdate: '1961-03-22',
    mobilenumber: 6666,
  },
  {
    id: 19,
    firstname: 'Timéa',
    name: 'Szabó',
    country: 'HU',
    birthdate: '1969-01-26',
    mobilenumber: 6666,
  },
  {
    id: 20,
    firstname: 'Natalia',
    name: 'Rusnov',
    country: 'RU',
    birthdate: '1965-08-09',
    mobilenumber: 0,
  },
  {
    id: 21,
    firstname: 'Bjørn',
    name: 'Larsson',
    country: 'DK',
    birthdate: '1964-11-11',
    mobilenumber: 6666,
  },
];
